"""empty message

Revision ID: 15ce0533c2e7
Revises: 3d20f5d2a65a
Create Date: 2021-06-09 09:01:00.285415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15ce0533c2e7'
down_revision = '3d20f5d2a65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_constraint('memes_categoryId_fkey', 'memes', type_='foreignkey')
    op.drop_column('memes', 'categoryId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('memes_categoryId_fkey', 'memes', 'categories', ['categoryId'], ['id'])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
