"""empty message

Revision ID: d46eddda4174
Revises: 6c456afbb73f
Create Date: 2021-06-09 13:17:23.785033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46eddda4174'
down_revision = '6c456afbb73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('purchaseId', sa.Integer(), nullable=False))
    op.drop_column('purchases', 'purchase_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchases', 'purchaseId')
    # ### end Alembic commands ###
