"""empty message

Revision ID: 6c456afbb73f
Revises: b3c397909395
Create Date: 2021-06-09 13:10:37.796855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c456afbb73f'
down_revision = 'b3c397909395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('purchase_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'purchase_id')
    # ### end Alembic commands ###
