"""empty message

Revision ID: b3c397909395
Revises: b61d3e4c7dd2
Create Date: 2021-06-09 10:10:27.118032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3c397909395'
down_revision = 'b61d3e4c7dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memesincart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('memeId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memeId'], ['memes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('memesInCart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memesInCart',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"memesInCart_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memeId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['memeId'], ['memes.id'], name='memesInCart_memeId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='memesInCart_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='memesInCart_pkey')
    )
    op.drop_table('memesincart')
    # ### end Alembic commands ###
