"""empty message

Revision ID: d3bfe1c603d1
Revises: a95c03c947f0
Create Date: 2021-06-02 14:40:19.637068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bfe1c603d1'
down_revision = 'a95c03c947f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
